# =========================
#  ZFS and File Systems
# =========================
vfs.zfs.vdev.min_auto_ashift=12        # Optimize SSD sector alignment

# =========================
#  Security
# =========================
security.bsd.see_other_uids=1
security.bsd.see_other_gids=0
security.bsd.see_jail_proc=0
security.bsd.unprivileged_read_msgbuf=0
security.bsd.unprivileged_proc_debug=0
kern.randompid=1
kern.corefile=/var/coredump/%N-%P.core

# =========================
#  Linux Compatibility
# =========================
compat.linux.osrelease=6.18.9

# =========================
#  Power Management
# =========================
#hw.acpi.lid_switch_state=S3       # Suspend when lid is closed
#hw.acpi.sleep_button_state=S3
#kern.sched.preempt_thresh=200     # Improve desktop responsiveness

# =========================
#  Desktop Responsiveness
# =========================
kern.sched.preempt_thresh=224
kern.sched.slice=3
vfs.usermount=1

# =========================
#  Network & TCP Optimization
# =========================
net.inet.tcp.functions_default=bbr
net.inet.tcp.bbr.software_pacing=1
net.inet.tcp.bbr.cwnd.initwin=32
net.inet.tcp.rack.pkt_delay=2
net.inet.tcp.fastopen.server_enable=1
net.inet.tcp.fastopen.client_enable=1
net.inet.tcp.syncookies=1
net.inet.ip.redirect=0
net.inet.ip.forwarding=1          # Disable it if not used as a router(Hotspot)
net.inet.ip.portrange.randomized=1
net.inet.tcp.msl=30000            # Faster TCP session recycle
net.inet.tcp.bbr.startup.loss_threshold=3000
